channels:
  - conda-forge
dependencies:
  - python=3.10
  - sphinx=5.0
  - contextily==1.3.0
  - dask==2022.11.0
  - geopandas==0.12.2
  - h3-py==3.7.4
  - pandas==1.5.3
  - pyarrow==11.0.0
  - scikit-mobility==1.3.1
